#!/usr/bin/env bash

alias tmux="tmux -L shdw -2 -f $SHDWDIR/rc/tmux.conf"
SHDWVIM="vim -p -u $SHDWDIR/rc/vimrc"
alias vim=${SHDWVIM}
alias python="PYTHONSTARTUP=$SHDWDIR/rc/pythonrc python"

# Compatibility with OSX which doesn't support --color
export CLICOLOR=1
ls --color=auto &> /dev/null && alias ls='ls -F --color' || alias ls='ls -F'

alias axel="axel -a"
alias diff="diff -y --suppress-common-lines"
alias find="LC_ALL=\"C\" find"
alias grep="LC_ALL=\"C\" grep --color"
alias mkdir="mkdir -p"

alias pid="ps -o pid --no-header -C"
alias sprunge="curl -F \"sprunge=<-\" http://sprunge.us"
alias please='sudo $(history -p !!)'
alias serve='python -m SimpleHTTPServer'

alias stats='ssh -tt parabox "/invia/bin/jump stats"'
alias ldrms='ssh -tt parabox "/invia/bin/jump ldpa1 3200"'

if [ ! -z ${SHDWUSER} ]; then

    # Parse the first field of the users file to find all user names
    SHDWUSERS=$(awk -F, '{printf("%s\n", $1)}' ${SHDWDIR}/shdws)

    # Check to see if the requested user is actually in the file
    if echo ${SHDWUSERS} | grep -q "\b$SHDWUSER\b" 2> /dev/null; then

        # Grab the whole config line for the requested user
        SHDWLINE=$(grep "^$SHDWUSER\b" ${SHDWDIR}/shdws)

        # Parse out the needed fields
        SHDWNAME=$(echo ${SHDWLINE} | awk -F, '{printf("%s\n", $2)}')
        SHDWEMAIL=$(echo ${SHDWLINE} | awk -F, '{printf("%s\n", $3)}')

        GITCONFIG=""
        GITCONFIG="${GITCONFIG} -c user.name=\"${SHDWNAME}\""
        GITCONFIG="${GITCONFIG} -c user.email=\"${SHDWEMAIL}\""
        GITCONFIG="${GITCONFIG} -c core.editor=\"${SHDWVIM}\""
        GITCONFIG="${GITCONFIG} -c push.default=simple"

        DIFFTOOL="${SHDWDIR}/bin/diff-highlight | less"
        GITCONFIG="${GITCONFIG} -c pager.log=\"${DIFFTOOL}\""
        GITCONFIG="${GITCONFIG} -c pager.show=\"${DIFFTOOL}\""
        GITCONFIG="${GITCONFIG} -c pager.diff=\"${DIFFTOOL}\""

        alias git="git ${GITCONFIG}"

    else
        echo "!!! WARNING: config user not found ($SHDWUSER) !!!"
    fi
fi

# vim:syntax=sh
